### ISSUE TITLE
Week 7 - Code review

### ISSUE THREAD

**Issue by SharonV33** [sahitj001/project-tech-team#10]
# Code review

## Name
sharon

## Class
tech2

## Feedback
ziet er goed uit, ik heb het geprobeerd te forken maar ik kan het project niet starten. kan aan mijn laptop liggen maar thats it

### Feedback specifiek op criterium 1 Project Tech
ziet eruit dat het goed gaat

### Feedback specifiek op criterium 2 Project Tech
super duidelijk! 

### Feedback specifiek op criterium 3 Project Tech
hier staat nog niets in maar dat zal nog wel komen

### Feedback specifiek op criterium 5 Project Tech
ik kan het project niet draaien, ik krijg een error bij het "node ./bin/www" command, ik kan dit bestand ook niet zo snel vinden in het project

### Feedback over andere dingen, zoals voor backend of frontend
kan ik niet naar kijken helaas

**Comment by ChunningTatum** [comment]
Thanks for the feedback, there was an error in package.json and that has been changed
