### ISSUE TITLE
Code Review Week 7

### ISSUE THREAD

**Issue by saralof** [sahitj001/project-tech-team#11]
# Code review

## Name
Sara Lof

## Class
Tech 2

## Feedback
Goed opweg, netjes ontwerp.

### Feedback specifiek op criterium 1 Project Tech
Het wordt goed bijgehouden, iedereen heeft zijn eigen branche en er is een development branche. Er worden al veel commits gedaan. 

### Feedback specifiek op criterium 2 Project Tech
De samenwerking is niet terug te vinden op de github, dus hierover kan ik niet goed oordelen.

### Feedback specifiek op criterium 3 Project Tech
Er is al een readme, er mist nog een installguide.

### Feedback specifiek op criterium 5 Project Tech
Prototype tot zover ziet er al goed uit.

**Comment by ChunningTatum** [comment]
Thank you for the feedback, made a code of conduct and installation guide
