### ISSUE TITLE
Code review Jordy

### ISSUE THREAD

**Issue by sahitj001** [sahitj001/project-tech-team#13]
---
name: Week 7 - Code review
about: Chun
title: Code review
labels: 'week-7, week-7-code-review'
---

# Code review

## Name
Jordy

## Class
Tech 2

## Feedback
Good teamwork

### Feedback specifiek op criterium 1 Project Tech
Ik zie branches en er wordt gemerged.

### Feedback specifiek op criterium 2 Project Tech
Er zijn nog geen afspraken gemaakt over code stijl en standaarden. Wel is er een .editorconfig.

### Feedback specifiek op criterium 3 Project Tech
Nog niks gedocumenteerd in de readme. Wel documenteren we op github Projects wat er nog gedaan moet worden.

### Feedback specifiek op criterium 5 Project Tech
-

### Feedback over andere dingen, zoals voor backend of frontend

**Comment by ChunningTatum** [comment]
Thank you for the feedback, working on the wiki has been added to the project trello
