### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Awana1** [sahitj001/project-tech-team#27]
# Code review
name: Week 7 - Code review
about: Code review voor team Sharon, Sara, Cherelle en Ouiaam

# Feedback specifiek op criterium 1 Project Tech
Er wordt gewerkt met git, github en branches.

# Feedback specifiek op criterium 2 Project Tech
ik zie alleen een master en een development branch. Wij hebben naast deze twee ook onze eigen branches. Daarin zet iedereen zijn eigen uitgewerkte functie erin. 

# Feedback specifiek op criterium 3 Project Tech
Meer documentatie 

# Feedback specifiek op criterium 5 Project Tech
Mooi begin

**Comment by ChunningTatum** [comment]
Thank you for the feedback
