### ISSUE TITLE
Feedback op beoordelingscriteria

### ISSUE THREAD

**Issue by rouws** [sahitj001/project-tech-team#7]
---
name: Week 7 - Code review
about: Code review on a classmate
title: Code review
labels: 'week-7, week-7-code-review'
---

# Code review

## Name
Sonja Rouwhorst

## Class
Docent

## Feedback

Goed begin, de basis staat klaar en jullie kunnen van start

### Feedback specifiek op criterium 1 Project Tech

ja top, ik zie een development branche en eigen feature branches lekker bezig

### Feedback specifiek op criterium 2 Project Tech

Heb je dit al gedaan? Beschrijf dit in je wiki

### Feedback specifiek op criterium 3 Project Tech

De readme is er, maar gaan jullie nog vullen ga ik vanuit

### Feedback specifiek op criterium 5 Project Tech

Mooi begin!

**Comment by ChunningTatum** [comment]
Thanks for the feedback, only the Wiki has to be done for now
